openapi: 3.0.0
info:
  title: Input Output data Specifications
  version: 1.0.0
components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: integer
          description: The ID (required for update).
        name:
          type: string
          description: The name (required for insert).
        parentId:
          type: integer
          description: The ID of the parent group (default is 0 for root).

    Doc:
      type: object
      properties:
        id:
          type: integer
          description: The ID (required for update).
        name:
          type: string
          description: The name (required for insert).
        groupId:
          type: integer
          description: The ID of the parent group (default is 0 for root).

    DocFile:
      type: object
      properties:
        id:
          type: integer
          description: The ID (required for update).
        dateCreated:
          type: string
          format: date-time
          description: The date when the docfile was updated.
        docId:
          type: integer
          description: The ID of the doc associated (required for insert).
        name:
          type: string
          description: The name (required for insert).
        userId:
          type: string
          description: The ID of the user (optional, if needed).
        isActive:
          type: integer
          description: Active status (optional, if needed)..
        fileType:
          type: string
          description: File type (optional, if needed).
